local mmu = require("mmu")
local json = require("cjson")

function printTable(tabl, wid)
	if not wid then wid = 1 end
	for i,v in pairs(tabl) do
		if type(v) == "table" then
			print(string.rep(" ", wid * 3) .. i .. " = {")
			printTable(v, wid + 1)
			print(string.rep(" ", wid * 3) .. "}")
		elseif type(v) == "string" then
			print(string.rep(" ", wid * 3) .. i .. " = \"" .. v .. "\"")
		elseif type(v) == "number" then
			print(string.rep(" ", wid * 3) .. i .. " = " .. v)
		end 
	end 
end

local function CPU()
	local f = io.open("dmgops.json","r")
	local d = f:read("*a")
	f:close()
	jdataP = json.decode(d).CBPrefixed
	jdataU = json.decode(d).Unprefixed
	--printTable(jdata.Unprefixed)
	
	local self = {
		--registers
		A = 0,
		B = 0,
		C = 0,
		D = 0,
		E = 0,
		H = 0,
		L = 0,
		F = 0,
		SP = 0,
		PC = 0,
		cycles = 0,
		mem = {}
	}
	cycles = 0
	local mem = mmu("Tetris.gb")
	self.mem = mem
	--local instructions = {}
	bor = bit.bor
band = bit.band
xor = bit.bxor
lshift = bit.lshift
rshift = bit.rshift

instructions =  {
function() cycles = cycles + 4 end,--no-op [0]
function() self.C = mem.getByte(self.PC) ; self.B = mem.getByte(self.PC+1); cycles = cycles + 12; self.PC = self.PC+ 2 end,--[1 0x1]
function() mem.setByte(self.A,(self.C+lshift(self.B,8))); cycles = cycles + 8 end,--[2 0x2]
function() error("unimplemented instruction 3(0x3)") end,--[3 0x3]
function() self.F = (band(self.B,0xF )+band( 1,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.B = self.B +  1; self.B = bit.band(self.B,0xFF) ; self.F = (self.B == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 4 end,--[4 0x4]
function() self.F= (((band(self.B,0xF)-band( 1,0xF)) < 0) and self.B > 0 ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.B = ((self.B- 1 > 0) and self.B- 1 or 0)  ;self.B = bit.band(self.B,0xFF) ; self.F = (self.B == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = bor(self.F,0x40) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[5 0x5]
function() self.B = mem.getByte(self.PC) ; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[6 0x6]
function() error("unimplemented instruction 7(0x7)") end,--[7 0x7]
function()  local temp = (mem.getByte(self.PC)+lshift(mem.getByte(self.PC+1),8)) ;mem.setByte(rshift(band(self.SP,0xFF00),8),temp) ;mem.setByte(band(self.SP,0xFF),temp+1); cycles = cycles + 20; self.PC = self.PC+ 2 end,--[8 0x8]
function() error("unimplemented instruction 9(0x9)") end,--[9 0x9]
function() self.A = mem.getByte((self.C+lshift(self.B,8))); cycles = cycles + 8 end,--[10 0xa]
function() error("unimplemented instruction 11(0xb)") end,--[11 0xb]
function() self.F = (band(self.C,0xF )+band( 1,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.C = self.C +  1; self.C = bit.band(self.C,0xFF) ; self.F = (self.C == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 4 end,--[12 0xc]
function() self.F= (((band(self.C,0xF)-band( 1,0xF)) < 0) and self.C > 0 ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.C = ((self.C- 1 > 0) and self.C- 1 or 0)  ;self.C = bit.band(self.C,0xFF) ; self.F = (self.C == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = bor(self.F,0x40) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[13 0xd]
function() self.C = mem.getByte(self.PC) ; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[14 0xe]
function() error("unimplemented instruction 15(0xf)") end,--[15 0xf]
function() error("unimplemented instruction 16(0x10)") end,--[16 0x10]
function() self.E = mem.getByte(self.PC) ; self.D = mem.getByte(self.PC+1); cycles = cycles + 12; self.PC = self.PC+ 2 end,--[17 0x11]
function() mem.setByte(self.A,(self.E+lshift(self.D,8))); cycles = cycles + 8 end,--[18 0x12]
function()  local temp = (lshift(self.D,8)+self.E) ;temp = temp+1; temp = bit.band(temp,0xFFFF) ; self.D = rshift(band(temp,0xFF00),8) ; self.E = band(temp,0xFF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 12 end,--[19 0x13]
function() self.F = (band(self.D,0xF )+band( 1,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.D = self.D +  1; self.D = bit.band(self.D,0xFF) ; self.F = (self.D == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 4 end,--[20 0x14]
function() self.F= (((band(self.D,0xF)-band( 1,0xF)) < 0) and self.D > 0 ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.D = ((self.D- 1 > 0) and self.D- 1 or 0)  ;self.D = bit.band(self.D,0xFF) ; self.F = (self.D == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = bor(self.F,0x40) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[21 0x15]
function() self.D = mem.getByte(self.PC) ; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[22 0x16]
function()  local temp = (band(self.F,0x10)>0 and 1 or 0) ; self.A = lshift(self.A, 1)  ; self.F = ((band(self.A, 256) == 0) and band(self.F,0xEF) or bor(self.F,0x10))  ;self.A = bor(self.A,temp) ; self.A = bit.band(self.A,0xFF) ; self.F = (self.A == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xDF) ; self.F = band(self.F,0xBF); cycles = cycles + 8 end,--[23 0x17]
function() self.PC = self.PC + mem.getSignedByte(self.PC); cycles = cycles + 8; self.PC = self.PC+ 1 end,--[24 0x18]
function() error("unimplemented instruction 25(0x19)") end,--[25 0x19]
function() self.A = mem.getByte((self.E+lshift(self.D,8))); cycles = cycles + 8 end,--[26 0x1a]
function() error("unimplemented instruction 27(0x1b)") end,--[27 0x1b]
function() self.F = (band(self.E,0xF )+band( 1,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.E = self.E +  1; self.E = bit.band(self.E,0xFF) ; self.F = (self.E == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 4 end,--[28 0x1c]
function() self.F= (((band(self.E,0xF)-band( 1,0xF)) < 0) and self.E > 0 ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.E = ((self.E- 1 > 0) and self.E- 1 or 0)  ;self.E = bit.band(self.E,0xFF) ; self.F = (self.E == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = bor(self.F,0x40) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[29 0x1d]
function() self.E = mem.getByte(self.PC) ; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[30 0x1e]
function() error("unimplemented instruction 31(0x1f)") end,--[31 0x1f]
function() if (band(self.F,0x80) == 0) then self.PC = self.PC + mem.getSignedByte(self.PC)  ; cycles = cycles +  4 end; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[32 0x20]
function() self.L = mem.getByte(self.PC) ; self.H = mem.getByte(self.PC+1); cycles = cycles + 12; self.PC = self.PC+ 2 end,--[33 0x21]
function()  local temp = (lshift(self.H,8)+self.L) ; mem.setByte(self.A,temp) ; temp = temp+1  ;temp = bit.band(temp,0xFFFF) ; self.H = rshift(band(temp,0xFF00),8) ; self.L = band(temp,0xFF) ; cycles = cycles + 8 end,--[34 0x22]
function()  local temp = (lshift(self.H,8)+self.L) ;temp = temp+1; temp = bit.band(temp,0xFFFF) ; self.H = rshift(band(temp,0xFF00),8) ; self.L = band(temp,0xFF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 12 end,--[35 0x23]
function() self.F = (band(self.H,0xF )+band( 1,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.H = self.H +  1; self.H = bit.band(self.H,0xFF) ; self.F = (self.H == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 4 end,--[36 0x24]
function() self.F= (((band(self.H,0xF)-band( 1,0xF)) < 0) and self.H > 0 ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.H = ((self.H- 1 > 0) and self.H- 1 or 0)  ;self.H = bit.band(self.H,0xFF) ; self.F = (self.H == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = bor(self.F,0x40) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[37 0x25]
function() self.H = mem.getByte(self.PC) ; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[38 0x26]
function() error("unimplemented instruction 39(0x27)") end,--[39 0x27]
function() if (band(self.F,0x80) > 0) then  self.PC = self.PC + mem.getSignedByte(self.PC)  ; cycles = cycles +  4 end; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[40 0x28]
function() error("unimplemented instruction 41(0x29)") end,--[41 0x29]
function()  local temp = (lshift(self.H,8)+self.L) ; self.A = mem.getByte(temp) ; temp = temp+1  ;temp = bit.band(temp,0xFFFF) ; self.H = rshift(band(temp,0xFF00),8) ; self.L = band(temp,0xFF); cycles = cycles + 8 end,--[42 0x2a]
function() error("unimplemented instruction 43(0x2b)") end,--[43 0x2b]
function() self.F = (band(self.L,0xF )+band( 1,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.L = self.L +  1; self.L = bit.band(self.L,0xFF) ; self.F = (self.L == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 4 end,--[44 0x2c]
function() self.F= (((band(self.L,0xF)-band( 1,0xF)) < 0) and self.L > 0 ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.L = ((self.L- 1 > 0) and self.L- 1 or 0)  ;self.L = bit.band(self.L,0xFF) ; self.F = (self.L == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = bor(self.F,0x40) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[45 0x2d]
function() self.L = mem.getByte(self.PC) ; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[46 0x2e]
function() error("unimplemented instruction 47(0x2f)") end,--[47 0x2f]
function() error("unimplemented instruction 48(0x30)") end,--[48 0x30]
function() self.SP = (mem.getByte(self.PC)+lshift(mem.getByte(self.PC+1),8)); cycles = cycles + 12; self.PC = self.PC+ 2 end,--[49 0x31]
function()  local temp = (lshift(self.H,8)+self.L) ; mem.setByte(self.A,temp) ; temp = temp-1  ;temp = bit.band(temp,0xFFFF) ; self.H = rshift(band(temp,0xFF00),8) ; self.L = band(temp,0xFF) ; cycles = cycles + 8 end,--[50 0x32]
function() error("unimplemented instruction 51(0x33)") end,--[51 0x33]
function() error("unimplemented instruction 52(0x34)") end,--[52 0x34]
function() error("unimplemented instruction 53(0x35)") end,--[53 0x35]
function() mem.setByte(mem.getByte(self.PC),(lshift(self.H,8)+self.L)); cycles = cycles + 12; self.PC = self.PC+ 1 end,--[54 0x36]
function() error("unimplemented instruction 55(0x37)") end,--[55 0x37]
function() error("unimplemented instruction 56(0x38)") end,--[56 0x38]
function() error("unimplemented instruction 57(0x39)") end,--[57 0x39]
function()  local temp = (lshift(self.H,8)+self.L) ; self.A = mem.getByte(temp) ; temp = temp-1  ;temp = bit.band(temp,0xFFFF) ; self.H = rshift(band(temp,0xFF00),8) ; self.L = band(temp,0xFF); cycles = cycles + 8 end,--[58 0x3a]
function() error("unimplemented instruction 59(0x3b)") end,--[59 0x3b]
function() self.F = (band(self.A,0xF )+band( 1,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.A = self.A +  1; self.A = bit.band(self.A,0xFF) ; self.F = (self.A == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF); cycles = cycles + 4 end,--[60 0x3c]
function() self.F= (((band(self.A,0xF)-band( 1,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF)  ;self.A = ((self.A- 1 > 0) and self.A- 1 or 0)  ;self.A = bit.band(self.A,0xFF) ; self.F = (self.A == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = bor(self.F,0x40) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[61 0x3d]
function() self.A = mem.getByte(self.PC); cycles = cycles + 8; self.PC = self.PC+ 1 end,--[62 0x3e]
function() error("unimplemented instruction 63(0x3f)") end,--[63 0x3f]
function() self.B = self.B; cycles = cycles + 4 end,--[64 0x40]
function() self.B = self.C; cycles = cycles + 4 end,--[65 0x41]
function() self.B = self.D; cycles = cycles + 4 end,--[66 0x42]
function() self.B = self.E; cycles = cycles + 4 end,--[67 0x43]
function() self.B = self.H; cycles = cycles + 4 end,--[68 0x44]
function() self.B = self.L; cycles = cycles + 4 end,--[69 0x45]
function() self.B = mem.getByte((lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[70 0x46]
function() self.B = self.A; cycles = cycles + 4 end,--[71 0x47]
function() self.C = self.B; cycles = cycles + 4 end,--[72 0x48]
function() self.C = self.C; cycles = cycles + 4 end,--[73 0x49]
function() self.C = self.D; cycles = cycles + 4 end,--[74 0x4a]
function() self.C = self.E; cycles = cycles + 4 end,--[75 0x4b]
function() self.C = self.H; cycles = cycles + 4 end,--[76 0x4c]
function() self.C = self.L; cycles = cycles + 4 end,--[77 0x4d]
function() self.C = mem.getByte((lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[78 0x4e]
function() self.C = self.A; cycles = cycles + 4 end,--[79 0x4f]
function() self.D = self.B; cycles = cycles + 4 end,--[80 0x50]
function() self.D = self.C; cycles = cycles + 4 end,--[81 0x51]
function() self.D = self.D; cycles = cycles + 4 end,--[82 0x52]
function() self.D = self.E; cycles = cycles + 4 end,--[83 0x53]
function() self.D = self.H; cycles = cycles + 4 end,--[84 0x54]
function() self.D = self.L; cycles = cycles + 4 end,--[85 0x55]
function() self.D = mem.getByte((lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[86 0x56]
function() self.D = self.A; cycles = cycles + 4 end,--[87 0x57]
function() self.E = self.B; cycles = cycles + 4 end,--[88 0x58]
function() self.E = self.C; cycles = cycles + 4 end,--[89 0x59]
function() self.E = self.D; cycles = cycles + 4 end,--[90 0x5a]
function() self.E = self.E; cycles = cycles + 4 end,--[91 0x5b]
function() self.E = self.H; cycles = cycles + 4 end,--[92 0x5c]
function() self.E = self.L; cycles = cycles + 4 end,--[93 0x5d]
function() self.E = mem.getByte((lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[94 0x5e]
function() self.E = self.A; cycles = cycles + 4 end,--[95 0x5f]
function() self.H = self.B; cycles = cycles + 4 end,--[96 0x60]
function() self.H = self.C; cycles = cycles + 4 end,--[97 0x61]
function() self.H = self.D; cycles = cycles + 4 end,--[98 0x62]
function() self.H = self.E; cycles = cycles + 4 end,--[99 0x63]
function() self.H = self.H; cycles = cycles + 4 end,--[100 0x64]
function() self.H = self.L; cycles = cycles + 4 end,--[101 0x65]
function() self.H = mem.getByte((lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[102 0x66]
function() self.H = self.A; cycles = cycles + 4 end,--[103 0x67]
function() self.L = self.B; cycles = cycles + 4 end,--[104 0x68]
function() self.L = self.C; cycles = cycles + 4 end,--[105 0x69]
function() self.L = self.D; cycles = cycles + 4 end,--[106 0x6a]
function() self.L = self.E; cycles = cycles + 4 end,--[107 0x6b]
function() self.L = self.H; cycles = cycles + 4 end,--[108 0x6c]
function() self.L = self.L; cycles = cycles + 4 end,--[109 0x6d]
function() self.L = mem.getByte((lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[110 0x6e]
function() self.L = self.A; cycles = cycles + 4 end,--[111 0x6f]
function() mem.setByte(self.B,(lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[112 0x70]
function() mem.setByte(self.C,(lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[113 0x71]
function() mem.setByte(self.D,(lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[114 0x72]
function() mem.setByte(self.E,(lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[115 0x73]
function() mem.setByte(self.H,(lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[116 0x74]
function() mem.setByte(self.L,(lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[117 0x75]
function() error("unimplemented instruction 118(0x76)") end,--[118 0x76]
function() mem.setByte(self.A,(lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[119 0x77]
function() self.A = self.B ; cycles = cycles + 4 end,--[120 0x78]
function() self.A = self.C ; cycles = cycles + 4 end,--[121 0x79]
function() self.A = self.D ; cycles = cycles + 4 end,--[122 0x7a]
function() self.A = self.E ; cycles = cycles + 4 end,--[123 0x7b]
function() self.A = self.H ; cycles = cycles + 4 end,--[124 0x7c]
function() self.A = self.L ; cycles = cycles + 4 end,--[125 0x7d]
function() self.A = mem.getByte((lshift(self.H,8)+self.L)); cycles = cycles + 8 end,--[126 0x7e]
function() self.A = self.A ; cycles = cycles + 4 end,--[127 0x7f]
function()  local temp = self.A+self.B ; self.F = (band(self.A,0xF )+band(self.B,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(self.B,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[128 0x80]
function()  local temp = self.A+self.C ; self.F = (band(self.A,0xF )+band(self.C,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(self.C,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[129 0x81]
function()  local temp = self.A+self.D ; self.F = (band(self.A,0xF )+band(self.D,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(self.D,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[130 0x82]
function()  local temp = self.A+self.E ; self.F = (band(self.A,0xF )+band(self.E,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(self.E,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[131 0x83]
function()  local temp = self.A+self.H ; self.F = (band(self.A,0xF )+band(self.H,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(self.H,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[132 0x84]
function()  local temp = self.A+self.L ; self.F = (band(self.A,0xF )+band(self.L,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(self.L,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[133 0x85]
function()  local t = mem.getByte((lshift(self.H,8)+self.L)) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 8 end,--[134 0x86]
function()  local temp = self.A+self.A ; self.F = (band(self.A,0xF )+band(self.A,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(self.A,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[135 0x87]
function()  local t = self.B+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[136 0x88]
function()  local t = self.C+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[137 0x89]
function()  local t = self.D+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[138 0x8a]
function()  local t = self.E+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[139 0x8b]
function()  local t = self.H+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[140 0x8c]
function()  local t = self.L+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[141 0x8d]
function()  local t = mem.getByte((lshift(self.H,8)+self.L))+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[142 0x8e]
function()  local t = self.A+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4 end,--[143 0x8f]
function()  local temp = ((self.A-self.B > 0) and self.A-self.B or 0) ; self.F= (((band(self.A,0xF)-band(self.B,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (self.A-self.B < 0) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = bor(self.F,0x40) ; self.A = temp; cycles = cycles + 4 end,--[144 0x90]
function()  local temp = ((self.A-self.C > 0) and self.A-self.C or 0) ; self.F= (((band(self.A,0xF)-band(self.C,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (self.A-self.C < 0) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = bor(self.F,0x40) ; self.A = temp; cycles = cycles + 4 end,--[145 0x91]
function()  local temp = ((self.A-self.D > 0) and self.A-self.D or 0) ; self.F= (((band(self.A,0xF)-band(self.D,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (self.A-self.D < 0) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = bor(self.F,0x40) ; self.A = temp; cycles = cycles + 4 end,--[146 0x92]
function()  local temp = ((self.A-self.E > 0) and self.A-self.E or 0) ; self.F= (((band(self.A,0xF)-band(self.E,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (self.A-self.E < 0) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = bor(self.F,0x40) ; self.A = temp; cycles = cycles + 4 end,--[147 0x93]
function()  local temp = ((self.A-self.H > 0) and self.A-self.H or 0) ; self.F= (((band(self.A,0xF)-band(self.H,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (self.A-self.H < 0) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = bor(self.F,0x40) ; self.A = temp; cycles = cycles + 4 end,--[148 0x94]
function()  local temp = ((self.A-self.L > 0) and self.A-self.L or 0) ; self.F= (((band(self.A,0xF)-band(self.L,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (self.A-self.L < 0) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = bor(self.F,0x40) ; self.A = temp; cycles = cycles + 4 end,--[149 0x95]
function() error("unimplemented instruction 150(0x96)") end,--[150 0x96]
function()  local temp = ((self.A-self.A > 0) and self.A-self.A or 0) ; self.F= (((band(self.A,0xF)-band(self.A,0xF)) < 0) and self.A > 0 ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (self.A-self.A < 0) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = bor(self.F,0x40) ; self.A = temp; cycles = cycles + 4 end,--[151 0x97]
function() error("unimplemented instruction 152(0x98)") end,--[152 0x98]
function() error("unimplemented instruction 153(0x99)") end,--[153 0x99]
function() error("unimplemented instruction 154(0x9a)") end,--[154 0x9a]
function() error("unimplemented instruction 155(0x9b)") end,--[155 0x9b]
function() error("unimplemented instruction 156(0x9c)") end,--[156 0x9c]
function() error("unimplemented instruction 157(0x9d)") end,--[157 0x9d]
function() error("unimplemented instruction 158(0x9e)") end,--[158 0x9e]
function() error("unimplemented instruction 159(0x9f)") end,--[159 0x9f]
function() error("unimplemented instruction 160(0xa0)") end,--[160 0xa0]
function() error("unimplemented instruction 161(0xa1)") end,--[161 0xa1]
function() error("unimplemented instruction 162(0xa2)") end,--[162 0xa2]
function() error("unimplemented instruction 163(0xa3)") end,--[163 0xa3]
function() error("unimplemented instruction 164(0xa4)") end,--[164 0xa4]
function() error("unimplemented instruction 165(0xa5)") end,--[165 0xa5]
function() error("unimplemented instruction 166(0xa6)") end,--[166 0xa6]
function() error("unimplemented instruction 167(0xa7)") end,--[167 0xa7]
function() error("unimplemented instruction 168(0xa8)") end,--[168 0xa8]
function() error("unimplemented instruction 169(0xa9)") end,--[169 0xa9]
function() error("unimplemented instruction 170(0xaa)") end,--[170 0xaa]
function() error("unimplemented instruction 171(0xab)") end,--[171 0xab]
function() error("unimplemented instruction 172(0xac)") end,--[172 0xac]
function() error("unimplemented instruction 173(0xad)") end,--[173 0xad]
function() error("unimplemented instruction 174(0xae)") end,--[174 0xae]
function() self.A = xor(self.A,self.A) ; self.F = (self.A == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xBF) ; self.F = band(self.F,0xDF) ; self.F = band(self.F,0xEF); cycles = cycles + 4 end,--[175 0xaf]
function() error("unimplemented instruction 176(0xb0)") end,--[176 0xb0]
function() error("unimplemented instruction 177(0xb1)") end,--[177 0xb1]
function() error("unimplemented instruction 178(0xb2)") end,--[178 0xb2]
function() error("unimplemented instruction 179(0xb3)") end,--[179 0xb3]
function() error("unimplemented instruction 180(0xb4)") end,--[180 0xb4]
function() error("unimplemented instruction 181(0xb5)") end,--[181 0xb5]
function() error("unimplemented instruction 182(0xb6)") end,--[182 0xb6]
function() error("unimplemented instruction 183(0xb7)") end,--[183 0xb7]
function()  local temp = self.A - self.B ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,self.B),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 4 end,--[184 0xb8]
function()  local temp = self.A - self.C ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,self.C),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 4 end,--[185 0xb9]
function()  local temp = self.A - self.D ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,self.D),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 4 end,--[186 0xba]
function()  local temp = self.A - self.E ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,self.E),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 4 end,--[187 0xbb]
function()  local temp = self.A - self.H ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,self.H),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 4 end,--[188 0xbc]
function()  local temp = self.A - self.L ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,self.L),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 4 end,--[189 0xbd]
function()  local t = mem.getByte((lshift(self.H,8)+self.L)) ;  local temp = self.A - t ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,t),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 8 end,--[190 0xbe]
function()  local temp = self.A - self.A ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,self.A),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 4 end,--[191 0xbf]
function() error("unimplemented instruction 192(0xc0)") end,--[192 0xc0]
function() self.C = mem.getByte(self.SP) ; self.SP=self.SP+1  ;self.B = mem.getByte(self.SP) ; self.SP=self.SP+1; cycles = cycles + 12 end,--[193 0xc1]
function() error("unimplemented instruction 194(0xc2)") end,--[194 0xc2]
function() error("unimplemented instruction 195(0xc3)") end,--[195 0xc3]
function() error("unimplemented instruction 196(0xc4)") end,--[196 0xc4]
function() self.SP=self.SP-1  ;mem.setByte(self.B,self.SP) ; self.SP=self.SP-1  ;mem.setByte(self.C,self.SP); cycles = cycles + 16 end,--[197 0xc5]
function()  local t = mem.getByte(self.PC) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 8; self.PC = self.PC+ 1 end,--[198 0xc6]
function() error("unimplemented instruction 199(0xc7)") end,--[199 0xc7]
function() error("unimplemented instruction 200(0xc8)") end,--[200 0xc8]
function()  local temp = mem.getByte(self.SP) ; self.SP = self.SP +  1; temp = (temp+lshift(mem.getByte(self.SP),8)) ; self.SP = self.SP +  1; self.PC = temp; cycles = cycles + 8 end,--[201 0xc9]
function() error("unimplemented instruction 202(0xca)") end,--[202 0xca]
function() error("unimplemented instruction 203(0xcb)") end,--[203 0xcb]
function() error("unimplemented instruction 204(0xcc)") end,--[204 0xcc]
function() self.SP = self.SP-2  ;mem.setByte(bit.band(self.PC+2,0xFF),self.SP) ; mem.setByte(bit.band(self.PC+2,0xFF00),self.SP+1) ; self.PC = (mem.getByte(self.PC)+lshift(mem.getByte(self.PC+1),8)); cycles = cycles + 12 end,--[205 0xcd]
function()  local t = mem.getByte(self.PC)+(band(self.F,0x10)>0 and 1 or 0) ;  local temp = self.A+t ; self.F = (band(self.A,0xF )+band(t,0xF ) > 0xF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (temp == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = (band(self.A,0xFF)+band(t,0xFF) > 0xFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.A = bit.band(temp,0xFF); cycles = cycles + 4; self.PC = self.PC+ 1 end,--[206 0xce]
function() error("unimplemented instruction 207(0xcf)") end,--[207 0xcf]
function() error("unimplemented instruction 208(0xd0)") end,--[208 0xd0]
function() self.E = mem.getByte(self.SP) ; self.SP=self.SP+1  ;self.D = mem.getByte(self.SP) ; self.SP=self.SP+1; cycles = cycles + 12 end,--[209 0xd1]
function() error("unimplemented instruction 210(0xd2)") end,--[210 0xd2]
function() error("unimplemented instruction 211(0xd3)") end,--[211 0xd3]
function() error("unimplemented instruction 212(0xd4)") end,--[212 0xd4]
function() self.SP=self.SP-1  ;mem.setByte(self.D,self.SP) ; self.SP=self.SP-1  ;mem.setByte(self.E,self.SP); cycles = cycles + 16 end,--[213 0xd5]
function() error("unimplemented instruction 214(0xd6)") end,--[214 0xd6]
function() error("unimplemented instruction 215(0xd7)") end,--[215 0xd7]
function() error("unimplemented instruction 216(0xd8)") end,--[216 0xd8]
function() error("unimplemented instruction 217(0xd9)") end,--[217 0xd9]
function() error("unimplemented instruction 218(0xda)") end,--[218 0xda]
function() error("unimplemented instruction 219(0xdb)") end,--[219 0xdb]
function() error("unimplemented instruction 220(0xdc)") end,--[220 0xdc]
function() error("unimplemented instruction 221(0xdd)") end,--[221 0xdd]
function() error("unimplemented instruction 222(0xde)") end,--[222 0xde]
function() error("unimplemented instruction 223(0xdf)") end,--[223 0xdf]
function() mem.setByte(self.A, (0xFF00+mem.getByte(self.PC))); cycles = cycles + 12; self.PC = self.PC+ 1 end,--[224 0xe0]
function() self.L = mem.getByte(self.SP) ; self.SP=self.SP+1  ;self.H = mem.getByte(self.SP) ; self.SP=self.SP+1; cycles = cycles + 12 end,--[225 0xe1]
function() mem.setByte(self.A, (0xFF00+self.C)); cycles = cycles + 8 end,--[226 0xe2]
function() error("unimplemented instruction 227(0xe3)") end,--[227 0xe3]
function() error("unimplemented instruction 228(0xe4)") end,--[228 0xe4]
function() self.SP=self.SP-1  ;mem.setByte(self.H,self.SP) ; self.SP=self.SP-1  ;mem.setByte(self.L,self.SP); cycles = cycles + 16 end,--[229 0xe5]
function() error("unimplemented instruction 230(0xe6)") end,--[230 0xe6]
function() error("unimplemented instruction 231(0xe7)") end,--[231 0xe7]
function() error("unimplemented instruction 232(0xe8)") end,--[232 0xe8]
function() error("unimplemented instruction 233(0xe9)") end,--[233 0xe9]
function() mem.setByte(self.A,(mem.getByte(self.PC)+lshift(mem.getByte(self.PC+1),8))); cycles = cycles + 16; self.PC = self.PC+ 2 end,--[234 0xea]
function() error("unimplemented instruction 235(0xeb)") end,--[235 0xeb]
function() error("unimplemented instruction 236(0xec)") end,--[236 0xec]
function() error("unimplemented instruction 237(0xed)") end,--[237 0xed]
function() error("unimplemented instruction 238(0xee)") end,--[238 0xee]
function() error("unimplemented instruction 239(0xef)") end,--[239 0xef]
function() self.A = mem.getByte( (0xFF00+mem.getByte(self.PC))); cycles = cycles + 12; self.PC = self.PC+ 1 end,--[240 0xf0]
function() self.F = mem.getByte(self.SP) ; self.SP=self.SP+1  ;self.A = mem.getByte(self.SP) ; self.SP=self.SP+1; cycles = cycles + 12 end,--[241 0xf1]
function() self.A = mem.getByte( (0xFF00+self.C)); cycles = cycles + 8 end,--[242 0xf2]
function() error("unimplemented instruction 243(0xf3)") end,--[243 0xf3]
function() error("unimplemented instruction 244(0xf4)") end,--[244 0xf4]
function() self.SP=self.SP-1  ;mem.setByte(self.A,self.SP) ; self.SP=self.SP-1  ;mem.setByte(self.F,self.SP); cycles = cycles + 16 end,--[245 0xf5]
function() error("unimplemented instruction 246(0xf6)") end,--[246 0xf6]
function() error("unimplemented instruction 247(0xf7)") end,--[247 0xf7]
function()  local temp = mem.getSignedByte(self.PC) ; self.F = (band(self.PC,0xFFF )+band(temp,0xFFF ) > 0xFFF ) and bor(self.F,0x20) or band(self.F,0xDF) ; self.F = (band(self.PC,0xFFFF)+band(temp,0xFFFF) > 0xFFFF) and bor(self.F,0x10) or band(self.F,0xEF) ; self.F = band(self.F,0xBF) ; self.F = band(self.F,0x7F) ; temp = bit.band(temp,0xFFFF) ;temp = temp + self.PC ; self.H = rshift(band(temp,0xFF00),8) ; self.L = band(temp,0xFF); cycles = cycles + 12; self.PC = self.PC+ 1 end,--[248 0xf8]
function() self.SP = (lshift(self.H,8)+self.L); cycles = cycles + 8 end,--[249 0xf9]
function() self.A = mem.getByte((mem.getByte(self.PC)+lshift(mem.getByte(self.PC+1),8))); cycles = cycles + 16; self.PC = self.PC+ 2 end,--[250 0xfa]
function() error("unimplemented instruction 251(0xfb)") end,--[251 0xfb]
function() error("unimplemented instruction 252(0xfc)") end,--[252 0xfc]
function() error("unimplemented instruction 253(0xfd)") end,--[253 0xfd]
function()  local t = mem.getByte(self.PC) ;  local temp = self.A - t ; self.F = temp<0 and 0x50 or 0x40 ; temp = band(temp,0xff); if temp == 0 then self.F = bor(self.F,0x80) end if band(xor(xor(self.A,t),temp),0x10)>0 then self.F = bor(self.F,0x20) end; cycles = cycles + 8; self.PC = self.PC+ 1 end,--[254 0xfe]
function() error("unimplemented instruction 255(0xff)") end,--[255 0xff]
}
	
	instructionsCB =  {
function() cycles = cycles + 4 end,--no-op [0]
function() error("unimplemented 0xCB instruction 1(0x1)") end,--[1 0x1]
function() error("unimplemented 0xCB instruction 2(0x2)") end,--[2 0x2]
function() error("unimplemented 0xCB instruction 3(0x3)") end,--[3 0x3]
function() error("unimplemented 0xCB instruction 4(0x4)") end,--[4 0x4]
function() error("unimplemented 0xCB instruction 5(0x5)") end,--[5 0x5]
function() error("unimplemented 0xCB instruction 6(0x6)") end,--[6 0x6]
function() error("unimplemented 0xCB instruction 7(0x7)") end,--[7 0x7]
function() error("unimplemented 0xCB instruction 8(0x8)") end,--[8 0x8]
function() error("unimplemented 0xCB instruction 9(0x9)") end,--[9 0x9]
function() error("unimplemented 0xCB instruction 10(0xa)") end,--[10 0xa]
function() error("unimplemented 0xCB instruction 11(0xb)") end,--[11 0xb]
function() error("unimplemented 0xCB instruction 12(0xc)") end,--[12 0xc]
function() error("unimplemented 0xCB instruction 13(0xd)") end,--[13 0xd]
function() error("unimplemented 0xCB instruction 14(0xe)") end,--[14 0xe]
function() error("unimplemented 0xCB instruction 15(0xf)") end,--[15 0xf]
function() error("unimplemented 0xCB instruction 16(0x10)") end,--[16 0x10]
function()  local temp = (band(self.F,0x10)>0 and 1 or 0) ; self.C = lshift(self.C, 1)  ; self.F = ((band(self.C, 256) == 0) and band(self.F,0xEF) or bor(self.F,0x10))  ;self.C = bor(self.C,temp) ; self.C = bit.band(self.C,0xFF) ; self.F = (self.C == 0) and bor(self.F,0x80) or band(self.F,0x7F) ; self.F = band(self.F,0xDF) ; self.F = band(self.F,0xBF); cycles = cycles + 8 end,--[17 0x11]
function() error("unimplemented 0xCB instruction 18(0x12)") end,--[18 0x12]
function() error("unimplemented 0xCB instruction 19(0x13)") end,--[19 0x13]
function() error("unimplemented 0xCB instruction 20(0x14)") end,--[20 0x14]
function() error("unimplemented 0xCB instruction 21(0x15)") end,--[21 0x15]
function() error("unimplemented 0xCB instruction 22(0x16)") end,--[22 0x16]
function() error("unimplemented 0xCB instruction 23(0x17)") end,--[23 0x17]
function() error("unimplemented 0xCB instruction 24(0x18)") end,--[24 0x18]
function() error("unimplemented 0xCB instruction 25(0x19)") end,--[25 0x19]
function() error("unimplemented 0xCB instruction 26(0x1a)") end,--[26 0x1a]
function() error("unimplemented 0xCB instruction 27(0x1b)") end,--[27 0x1b]
function() error("unimplemented 0xCB instruction 28(0x1c)") end,--[28 0x1c]
function() error("unimplemented 0xCB instruction 29(0x1d)") end,--[29 0x1d]
function() error("unimplemented 0xCB instruction 30(0x1e)") end,--[30 0x1e]
function() error("unimplemented 0xCB instruction 31(0x1f)") end,--[31 0x1f]
function() error("unimplemented 0xCB instruction 32(0x20)") end,--[32 0x20]
function() error("unimplemented 0xCB instruction 33(0x21)") end,--[33 0x21]
function() error("unimplemented 0xCB instruction 34(0x22)") end,--[34 0x22]
function() error("unimplemented 0xCB instruction 35(0x23)") end,--[35 0x23]
function() error("unimplemented 0xCB instruction 36(0x24)") end,--[36 0x24]
function() error("unimplemented 0xCB instruction 37(0x25)") end,--[37 0x25]
function() error("unimplemented 0xCB instruction 38(0x26)") end,--[38 0x26]
function() error("unimplemented 0xCB instruction 39(0x27)") end,--[39 0x27]
function() error("unimplemented 0xCB instruction 40(0x28)") end,--[40 0x28]
function() error("unimplemented 0xCB instruction 41(0x29)") end,--[41 0x29]
function() error("unimplemented 0xCB instruction 42(0x2a)") end,--[42 0x2a]
function() error("unimplemented 0xCB instruction 43(0x2b)") end,--[43 0x2b]
function() error("unimplemented 0xCB instruction 44(0x2c)") end,--[44 0x2c]
function() error("unimplemented 0xCB instruction 45(0x2d)") end,--[45 0x2d]
function() error("unimplemented 0xCB instruction 46(0x2e)") end,--[46 0x2e]
function() error("unimplemented 0xCB instruction 47(0x2f)") end,--[47 0x2f]
function() error("unimplemented 0xCB instruction 48(0x30)") end,--[48 0x30]
function() error("unimplemented 0xCB instruction 49(0x31)") end,--[49 0x31]
function() error("unimplemented 0xCB instruction 50(0x32)") end,--[50 0x32]
function() error("unimplemented 0xCB instruction 51(0x33)") end,--[51 0x33]
function() error("unimplemented 0xCB instruction 52(0x34)") end,--[52 0x34]
function() error("unimplemented 0xCB instruction 53(0x35)") end,--[53 0x35]
function() error("unimplemented 0xCB instruction 54(0x36)") end,--[54 0x36]
function() error("unimplemented 0xCB instruction 55(0x37)") end,--[55 0x37]
function() error("unimplemented 0xCB instruction 56(0x38)") end,--[56 0x38]
function() error("unimplemented 0xCB instruction 57(0x39)") end,--[57 0x39]
function() error("unimplemented 0xCB instruction 58(0x3a)") end,--[58 0x3a]
function() error("unimplemented 0xCB instruction 59(0x3b)") end,--[59 0x3b]
function() error("unimplemented 0xCB instruction 60(0x3c)") end,--[60 0x3c]
function() error("unimplemented 0xCB instruction 61(0x3d)") end,--[61 0x3d]
function() error("unimplemented 0xCB instruction 62(0x3e)") end,--[62 0x3e]
function() error("unimplemented 0xCB instruction 63(0x3f)") end,--[63 0x3f]
function() error("unimplemented 0xCB instruction 64(0x40)") end,--[64 0x40]
function() error("unimplemented 0xCB instruction 65(0x41)") end,--[65 0x41]
function() error("unimplemented 0xCB instruction 66(0x42)") end,--[66 0x42]
function() error("unimplemented 0xCB instruction 67(0x43)") end,--[67 0x43]
function() error("unimplemented 0xCB instruction 68(0x44)") end,--[68 0x44]
function() error("unimplemented 0xCB instruction 69(0x45)") end,--[69 0x45]
function() error("unimplemented 0xCB instruction 70(0x46)") end,--[70 0x46]
function() error("unimplemented 0xCB instruction 71(0x47)") end,--[71 0x47]
function() error("unimplemented 0xCB instruction 72(0x48)") end,--[72 0x48]
function() error("unimplemented 0xCB instruction 73(0x49)") end,--[73 0x49]
function() error("unimplemented 0xCB instruction 74(0x4a)") end,--[74 0x4a]
function() error("unimplemented 0xCB instruction 75(0x4b)") end,--[75 0x4b]
function() error("unimplemented 0xCB instruction 76(0x4c)") end,--[76 0x4c]
function() error("unimplemented 0xCB instruction 77(0x4d)") end,--[77 0x4d]
function() error("unimplemented 0xCB instruction 78(0x4e)") end,--[78 0x4e]
function() error("unimplemented 0xCB instruction 79(0x4f)") end,--[79 0x4f]
function() error("unimplemented 0xCB instruction 80(0x50)") end,--[80 0x50]
function() error("unimplemented 0xCB instruction 81(0x51)") end,--[81 0x51]
function() error("unimplemented 0xCB instruction 82(0x52)") end,--[82 0x52]
function() error("unimplemented 0xCB instruction 83(0x53)") end,--[83 0x53]
function() error("unimplemented 0xCB instruction 84(0x54)") end,--[84 0x54]
function() error("unimplemented 0xCB instruction 85(0x55)") end,--[85 0x55]
function() error("unimplemented 0xCB instruction 86(0x56)") end,--[86 0x56]
function() error("unimplemented 0xCB instruction 87(0x57)") end,--[87 0x57]
function() error("unimplemented 0xCB instruction 88(0x58)") end,--[88 0x58]
function() error("unimplemented 0xCB instruction 89(0x59)") end,--[89 0x59]
function() error("unimplemented 0xCB instruction 90(0x5a)") end,--[90 0x5a]
function() error("unimplemented 0xCB instruction 91(0x5b)") end,--[91 0x5b]
function() error("unimplemented 0xCB instruction 92(0x5c)") end,--[92 0x5c]
function() error("unimplemented 0xCB instruction 93(0x5d)") end,--[93 0x5d]
function() error("unimplemented 0xCB instruction 94(0x5e)") end,--[94 0x5e]
function() error("unimplemented 0xCB instruction 95(0x5f)") end,--[95 0x5f]
function() error("unimplemented 0xCB instruction 96(0x60)") end,--[96 0x60]
function() error("unimplemented 0xCB instruction 97(0x61)") end,--[97 0x61]
function() error("unimplemented 0xCB instruction 98(0x62)") end,--[98 0x62]
function() error("unimplemented 0xCB instruction 99(0x63)") end,--[99 0x63]
function() error("unimplemented 0xCB instruction 100(0x64)") end,--[100 0x64]
function() error("unimplemented 0xCB instruction 101(0x65)") end,--[101 0x65]
function() error("unimplemented 0xCB instruction 102(0x66)") end,--[102 0x66]
function() error("unimplemented 0xCB instruction 103(0x67)") end,--[103 0x67]
function() error("unimplemented 0xCB instruction 104(0x68)") end,--[104 0x68]
function() error("unimplemented 0xCB instruction 105(0x69)") end,--[105 0x69]
function() error("unimplemented 0xCB instruction 106(0x6a)") end,--[106 0x6a]
function() error("unimplemented 0xCB instruction 107(0x6b)") end,--[107 0x6b]
function() error("unimplemented 0xCB instruction 108(0x6c)") end,--[108 0x6c]
function() error("unimplemented 0xCB instruction 109(0x6d)") end,--[109 0x6d]
function() error("unimplemented 0xCB instruction 110(0x6e)") end,--[110 0x6e]
function() error("unimplemented 0xCB instruction 111(0x6f)") end,--[111 0x6f]
function() error("unimplemented 0xCB instruction 112(0x70)") end,--[112 0x70]
function() error("unimplemented 0xCB instruction 113(0x71)") end,--[113 0x71]
function() error("unimplemented 0xCB instruction 114(0x72)") end,--[114 0x72]
function() error("unimplemented 0xCB instruction 115(0x73)") end,--[115 0x73]
function() error("unimplemented 0xCB instruction 116(0x74)") end,--[116 0x74]
function() error("unimplemented 0xCB instruction 117(0x75)") end,--[117 0x75]
function() error("unimplemented 0xCB instruction 118(0x76)") end,--[118 0x76]
function() error("unimplemented 0xCB instruction 119(0x77)") end,--[119 0x77]
function() error("unimplemented 0xCB instruction 120(0x78)") end,--[120 0x78]
function() error("unimplemented 0xCB instruction 121(0x79)") end,--[121 0x79]
function() error("unimplemented 0xCB instruction 122(0x7a)") end,--[122 0x7a]
function() error("unimplemented 0xCB instruction 123(0x7b)") end,--[123 0x7b]
function() self.F = (band(self.H, 128) == 0) and bor(self.F,0x80) or band(self.F,0x7F); cycles = cycles + 8 end,--[124 0x7c]
function() error("unimplemented 0xCB instruction 125(0x7d)") end,--[125 0x7d]
function() error("unimplemented 0xCB instruction 126(0x7e)") end,--[126 0x7e]
function() error("unimplemented 0xCB instruction 127(0x7f)") end,--[127 0x7f]
function() error("unimplemented 0xCB instruction 128(0x80)") end,--[128 0x80]
function() error("unimplemented 0xCB instruction 129(0x81)") end,--[129 0x81]
function() error("unimplemented 0xCB instruction 130(0x82)") end,--[130 0x82]
function() error("unimplemented 0xCB instruction 131(0x83)") end,--[131 0x83]
function() error("unimplemented 0xCB instruction 132(0x84)") end,--[132 0x84]
function() error("unimplemented 0xCB instruction 133(0x85)") end,--[133 0x85]
function() error("unimplemented 0xCB instruction 134(0x86)") end,--[134 0x86]
function() error("unimplemented 0xCB instruction 135(0x87)") end,--[135 0x87]
function() error("unimplemented 0xCB instruction 136(0x88)") end,--[136 0x88]
function() error("unimplemented 0xCB instruction 137(0x89)") end,--[137 0x89]
function() error("unimplemented 0xCB instruction 138(0x8a)") end,--[138 0x8a]
function() error("unimplemented 0xCB instruction 139(0x8b)") end,--[139 0x8b]
function() error("unimplemented 0xCB instruction 140(0x8c)") end,--[140 0x8c]
function() error("unimplemented 0xCB instruction 141(0x8d)") end,--[141 0x8d]
function() error("unimplemented 0xCB instruction 142(0x8e)") end,--[142 0x8e]
function() error("unimplemented 0xCB instruction 143(0x8f)") end,--[143 0x8f]
function() error("unimplemented 0xCB instruction 144(0x90)") end,--[144 0x90]
function() error("unimplemented 0xCB instruction 145(0x91)") end,--[145 0x91]
function() error("unimplemented 0xCB instruction 146(0x92)") end,--[146 0x92]
function() error("unimplemented 0xCB instruction 147(0x93)") end,--[147 0x93]
function() error("unimplemented 0xCB instruction 148(0x94)") end,--[148 0x94]
function() error("unimplemented 0xCB instruction 149(0x95)") end,--[149 0x95]
function() error("unimplemented 0xCB instruction 150(0x96)") end,--[150 0x96]
function() error("unimplemented 0xCB instruction 151(0x97)") end,--[151 0x97]
function() error("unimplemented 0xCB instruction 152(0x98)") end,--[152 0x98]
function() error("unimplemented 0xCB instruction 153(0x99)") end,--[153 0x99]
function() error("unimplemented 0xCB instruction 154(0x9a)") end,--[154 0x9a]
function() error("unimplemented 0xCB instruction 155(0x9b)") end,--[155 0x9b]
function() error("unimplemented 0xCB instruction 156(0x9c)") end,--[156 0x9c]
function() error("unimplemented 0xCB instruction 157(0x9d)") end,--[157 0x9d]
function() error("unimplemented 0xCB instruction 158(0x9e)") end,--[158 0x9e]
function() error("unimplemented 0xCB instruction 159(0x9f)") end,--[159 0x9f]
function() error("unimplemented 0xCB instruction 160(0xa0)") end,--[160 0xa0]
function() error("unimplemented 0xCB instruction 161(0xa1)") end,--[161 0xa1]
function() error("unimplemented 0xCB instruction 162(0xa2)") end,--[162 0xa2]
function() error("unimplemented 0xCB instruction 163(0xa3)") end,--[163 0xa3]
function() error("unimplemented 0xCB instruction 164(0xa4)") end,--[164 0xa4]
function() error("unimplemented 0xCB instruction 165(0xa5)") end,--[165 0xa5]
function() error("unimplemented 0xCB instruction 166(0xa6)") end,--[166 0xa6]
function() error("unimplemented 0xCB instruction 167(0xa7)") end,--[167 0xa7]
function() error("unimplemented 0xCB instruction 168(0xa8)") end,--[168 0xa8]
function() error("unimplemented 0xCB instruction 169(0xa9)") end,--[169 0xa9]
function() error("unimplemented 0xCB instruction 170(0xaa)") end,--[170 0xaa]
function() error("unimplemented 0xCB instruction 171(0xab)") end,--[171 0xab]
function() error("unimplemented 0xCB instruction 172(0xac)") end,--[172 0xac]
function() error("unimplemented 0xCB instruction 173(0xad)") end,--[173 0xad]
function() error("unimplemented 0xCB instruction 174(0xae)") end,--[174 0xae]
function() error("unimplemented 0xCB instruction 175(0xaf)") end,--[175 0xaf]
function() error("unimplemented 0xCB instruction 176(0xb0)") end,--[176 0xb0]
function() error("unimplemented 0xCB instruction 177(0xb1)") end,--[177 0xb1]
function() error("unimplemented 0xCB instruction 178(0xb2)") end,--[178 0xb2]
function() error("unimplemented 0xCB instruction 179(0xb3)") end,--[179 0xb3]
function() error("unimplemented 0xCB instruction 180(0xb4)") end,--[180 0xb4]
function() error("unimplemented 0xCB instruction 181(0xb5)") end,--[181 0xb5]
function() error("unimplemented 0xCB instruction 182(0xb6)") end,--[182 0xb6]
function() error("unimplemented 0xCB instruction 183(0xb7)") end,--[183 0xb7]
function() error("unimplemented 0xCB instruction 184(0xb8)") end,--[184 0xb8]
function() error("unimplemented 0xCB instruction 185(0xb9)") end,--[185 0xb9]
function() error("unimplemented 0xCB instruction 186(0xba)") end,--[186 0xba]
function() error("unimplemented 0xCB instruction 187(0xbb)") end,--[187 0xbb]
function() error("unimplemented 0xCB instruction 188(0xbc)") end,--[188 0xbc]
function() error("unimplemented 0xCB instruction 189(0xbd)") end,--[189 0xbd]
function() error("unimplemented 0xCB instruction 190(0xbe)") end,--[190 0xbe]
function() error("unimplemented 0xCB instruction 191(0xbf)") end,--[191 0xbf]
function() error("unimplemented 0xCB instruction 192(0xc0)") end,--[192 0xc0]
function() error("unimplemented 0xCB instruction 193(0xc1)") end,--[193 0xc1]
function() error("unimplemented 0xCB instruction 194(0xc2)") end,--[194 0xc2]
function() error("unimplemented 0xCB instruction 195(0xc3)") end,--[195 0xc3]
function() error("unimplemented 0xCB instruction 196(0xc4)") end,--[196 0xc4]
function() error("unimplemented 0xCB instruction 197(0xc5)") end,--[197 0xc5]
function() error("unimplemented 0xCB instruction 198(0xc6)") end,--[198 0xc6]
function() error("unimplemented 0xCB instruction 199(0xc7)") end,--[199 0xc7]
function() error("unimplemented 0xCB instruction 200(0xc8)") end,--[200 0xc8]
function() error("unimplemented 0xCB instruction 201(0xc9)") end,--[201 0xc9]
function() error("unimplemented 0xCB instruction 202(0xca)") end,--[202 0xca]
function() error("unimplemented 0xCB instruction 203(0xcb)") end,--[203 0xcb]
function() error("unimplemented 0xCB instruction 204(0xcc)") end,--[204 0xcc]
function() error("unimplemented 0xCB instruction 205(0xcd)") end,--[205 0xcd]
function() error("unimplemented 0xCB instruction 206(0xce)") end,--[206 0xce]
function() error("unimplemented 0xCB instruction 207(0xcf)") end,--[207 0xcf]
function() error("unimplemented 0xCB instruction 208(0xd0)") end,--[208 0xd0]
function() error("unimplemented 0xCB instruction 209(0xd1)") end,--[209 0xd1]
function() error("unimplemented 0xCB instruction 210(0xd2)") end,--[210 0xd2]
function() error("unimplemented 0xCB instruction 211(0xd3)") end,--[211 0xd3]
function() error("unimplemented 0xCB instruction 212(0xd4)") end,--[212 0xd4]
function() error("unimplemented 0xCB instruction 213(0xd5)") end,--[213 0xd5]
function() error("unimplemented 0xCB instruction 214(0xd6)") end,--[214 0xd6]
function() error("unimplemented 0xCB instruction 215(0xd7)") end,--[215 0xd7]
function() error("unimplemented 0xCB instruction 216(0xd8)") end,--[216 0xd8]
function() error("unimplemented 0xCB instruction 217(0xd9)") end,--[217 0xd9]
function() error("unimplemented 0xCB instruction 218(0xda)") end,--[218 0xda]
function() error("unimplemented 0xCB instruction 219(0xdb)") end,--[219 0xdb]
function() error("unimplemented 0xCB instruction 220(0xdc)") end,--[220 0xdc]
function() error("unimplemented 0xCB instruction 221(0xdd)") end,--[221 0xdd]
function() error("unimplemented 0xCB instruction 222(0xde)") end,--[222 0xde]
function() error("unimplemented 0xCB instruction 223(0xdf)") end,--[223 0xdf]
function() error("unimplemented 0xCB instruction 224(0xe0)") end,--[224 0xe0]
function() error("unimplemented 0xCB instruction 225(0xe1)") end,--[225 0xe1]
function() error("unimplemented 0xCB instruction 226(0xe2)") end,--[226 0xe2]
function() error("unimplemented 0xCB instruction 227(0xe3)") end,--[227 0xe3]
function() error("unimplemented 0xCB instruction 228(0xe4)") end,--[228 0xe4]
function() error("unimplemented 0xCB instruction 229(0xe5)") end,--[229 0xe5]
function() error("unimplemented 0xCB instruction 230(0xe6)") end,--[230 0xe6]
function() error("unimplemented 0xCB instruction 231(0xe7)") end,--[231 0xe7]
function() error("unimplemented 0xCB instruction 232(0xe8)") end,--[232 0xe8]
function() error("unimplemented 0xCB instruction 233(0xe9)") end,--[233 0xe9]
function() error("unimplemented 0xCB instruction 234(0xea)") end,--[234 0xea]
function() error("unimplemented 0xCB instruction 235(0xeb)") end,--[235 0xeb]
function() error("unimplemented 0xCB instruction 236(0xec)") end,--[236 0xec]
function() error("unimplemented 0xCB instruction 237(0xed)") end,--[237 0xed]
function() error("unimplemented 0xCB instruction 238(0xee)") end,--[238 0xee]
function() error("unimplemented 0xCB instruction 239(0xef)") end,--[239 0xef]
function() error("unimplemented 0xCB instruction 240(0xf0)") end,--[240 0xf0]
function() error("unimplemented 0xCB instruction 241(0xf1)") end,--[241 0xf1]
function() error("unimplemented 0xCB instruction 242(0xf2)") end,--[242 0xf2]
function() error("unimplemented 0xCB instruction 243(0xf3)") end,--[243 0xf3]
function() error("unimplemented 0xCB instruction 244(0xf4)") end,--[244 0xf4]
function() error("unimplemented 0xCB instruction 245(0xf5)") end,--[245 0xf5]
function() error("unimplemented 0xCB instruction 246(0xf6)") end,--[246 0xf6]
function() error("unimplemented 0xCB instruction 247(0xf7)") end,--[247 0xf7]
function() error("unimplemented 0xCB instruction 248(0xf8)") end,--[248 0xf8]
function() error("unimplemented 0xCB instruction 249(0xf9)") end,--[249 0xf9]
function() error("unimplemented 0xCB instruction 250(0xfa)") end,--[250 0xfa]
function() error("unimplemented 0xCB instruction 251(0xfb)") end,--[251 0xfb]
function() error("unimplemented 0xCB instruction 252(0xfc)") end,--[252 0xfc]
function() error("unimplemented 0xCB instruction 253(0xfd)") end,--[253 0xfd]
function() error("unimplemented 0xCB instruction 254(0xfe)") end,--[254 0xfe]
function() error("unimplemented 0xCB instruction 255(0xff)") end,--[255 0xff]
}
	
	function self.executeInstruction(p)
		local pr = print
		if not p then
			print = function() end
		end
		print("-------fetch inst--------")
		local inst = mem.getByte(self.PC)+1
		print("0x"..string.format("%x",inst-1))
		self.PC = self.PC + 1
		if inst-1 == 0xcb then
			inst2 = mem.getByte(self.PC)+1
			print(jdataP[inst2].Name)
			print("-------------------------")
			print("\t0x"..string.format("%x",inst2-1))
			self.PC = self.PC + 1
			if instructionsCB[inst2] then
				instructionsCB[inst2]()
			else
				--error("unimplemented instruction: "..inst.." 0x"..string.format("%x",inst).."")
				print("no instruction")
			end	
		else
			print(jdataU[inst].Name)
			print("-------------------------")
			if instructions[inst] then
				instructions[inst]()
			else
				--error("unimplemented instruction: "..inst.." 0x"..string.format("%x",inst).."")
				print("no instruction")
			end
		end
		print = pr
		self.cycles = cycles
	end
	
	function self.runInstruction(inst)
		print("Ruinning 0x"..string.format("%x",inst))
		if instructions[inst+1] then
			instructions[inst+1]()
		else
			--error("unimplemented instruction: "..inst.." 0x"..string.format("%x",inst).."")
			print("no instruction")
		end
	end
	
	--[[instructions = {
		[0 ] = function() cycles = cycles + 4 end,--no-op
		[33] = function() cycles = cycles + 12 ; self.H = mem.getByte(self.PC); self.L = mem.getByte(self.PC+1) ; self.PC = self.PC + 2 end,
		[49] = function() cycles = cycles + 4 ; self.SP = mem.getByte(self.PC)+bit.lshift(mem.getByte(self.PC+1),8) ; self.PC = self.PC + 2 end,
		[175] = function() cycles = cycles + 4 ; self.A = bit.bxor(self.A,self.A) end
	}]]
	
	return self
end

return CPU